version: '2'
services:
    borovetsblog-app:
        image: borovetsblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://borovetsblog-mysql:3306/borovetsblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    borovetsblog-mysql:
        extends:
            file: mysql.yml
            service: borovetsblog-mysql
